language: python

sudo: false

addons:
  firefox: "59.0"

python:
  - 2.7

cache:
  pip: true
  directories:
    - buildout-cache/downloads
    - buildout-cache/eggs

before_install:  
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz 
    - mkdir geckodriver && tar zxvf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver 
    - export PATH=$PATH:$PWD/geckodriver

install:
  - easy_install --version
  - pip install setuptools==33.1.1
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg --setuptools-version=33.1.1 --version=2.10.0
  - bin/buildout -Nc travis.cfg

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - bin/test 

after_success:
  - bin/coverage run bin/test
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
