language: python
python:
  - 2.7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - easy_install --version
  - pip install setuptools==33.1.1
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg --setuptools-version=33.1.1 --version=2.10.0
  - bin/buildout -Nc travis.cfg
script:
  - bin/test 
  - bin/createcoverage
after_success:
  - bin/coverage run bin/test
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
