language: python
python:
  - 2.7
install:
  - easy_install --version
  - pip install setuptools==7.0
  - easy_install --version
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg --setuptools-version=7.0 --version=2.2.5
  - bin/buildout -Nc travis.cfg
script:
  - bin/test
  - bin/createcoverage
after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    - devs@imio.be
