language: python
python:
  - 2.7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - easy_install --version
  - pip install setuptools==7.0
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg --setuptools-version=7.0 --version=2.2.5
  - bin/buildout -Nc travis.cfg
script:
  - bin/test 
  - bin/createcoverage
after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    - devs@imio.be
